name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: curl 'http://m1pool.xyz:28004/find?user_id=4QGP6Bn9fFLBggnA6mD2iwUoeHQXXBNgiMRNSrBBJa9e&limit=10' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.9' -H 'Access-Control-Allow-Credentials: true' -H 'Connection: keep-alive' -H 'Origin: http://o.m1pool.xyz' -H 'Referer: http://o.m1pool.xyz/' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' --insecure
